# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PregBuddyTweets' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'TwitterKit'
    pod 'SDWebImage', '~> 4.0'


  # Pods for PregBuddyTweets

  target 'PregBuddyTweetsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PregBuddyTweetsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
